targets:
  $default:
    sources:
      - integration_test/**   # By default, build runner will not generate code in the integration folder
      - test/**               # so we override paths for code generation here
      - lib/**
      - $package$
    builders:
      bdd_widget_test|featureBuilder:
        options:
          includeIntegrationTestBinding: false # if false, integration test will not include binding; default is true
          stepFolderName: step # this trick is required to share steps between widget and integration tests
          # relativeToTestFolder: false # if false, steps will be generated in the root of the package; default is true
          # testMethodName: customTestMethodName
          # addHooks: true # if true, hooks will be added to the test; default is false
          # hookFolderName: bdd_hooks
          # include: package:<package1>/bdd_options.yaml # you may add defaul external steps with this line
          externalSteps:                                    # or list only steps that you need
            # - package:<package2>/step/i_see_text.dart
            # - package:<package2>/step/i_dont_see_text.dart
            # - package:<package2>/step/i_see_multiple_texts.dart
            # - package:<package2>/step/i_tap_text.dart
            # - package:<package2>/step/i_see_icon.dart
            # - package:<package2>/step/i_dont_see_icon.dart
            # - package:<package2>/step/i_tap_icon.dart
            # - package:<package2>/step/i_see_rich_text.dart
            # - package:<package2>/step/i_dont_see_rich_text.dart
            # - package:<package2>/step/i_see_widget.dart
            # - package:<package2>/step/i_dont_see_widget.dart
            # - package:<package2>/step/i_see_exactly_widgets.dart
            # - package:<package2>/step/i_see_multiple_widgets.dart
            # - package:<package2>/step/i_enter_into_input_field.dart
            # - package:<package2>/step/i_see_disabled_elevated_button.dart
            # - package:<package2>/step/i_see_enabled_elevated_button.dart
            # - package:<package2>/step/i_wait.dart
            # - package:<package2>/step/i_dismiss_the_page.dart
        generate_for:
          - test/**
          - integration_test/**
        